name: Build project

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Runnning build script (release)
      shell: bash
      run: |
        bash ./build-module.sh

    - name: Runnning build script (debug)
      shell: bash
      run: |
        bash ./build-module.sh -debug

    - name: Parse tag name
      run: echo "TAG_NAME=$(cat module/backtap/module.prop | grep version= | cut -d= -f2 -)" >> $GITHUB_ENV

    - name: Generate release title
      run: echo "RTITLE=$(git log -n 1 --oneline | cut -d' ' -f2- -)"  >> $GITHUB_ENV

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
        tag_name: ${{ env.TAG_NAME }}
        name: ${{ env.RTITLE }}
        fail_on_unmatched_files: true
        body: "Only flash this module on phones that are supported. I am not responsible for any damage to your hardware."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

